# Generated by Django 3.2 on 2021-05-19 03:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0002_rename_shop_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='counties',
            fields=[
                ('county_1', models.CharField(max_length=25)),
                ('county_1_2', models.CharField(max_length=254)),
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
